# Generated by Django 4.2.1 on 2023-06-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAddress',
            new_name='Mailing_list',
        ),
    ]
