# Generated by Django 4.2.1 on 2023-06-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_email_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_list',
        ),
        migrations.DeleteModel(
            name='Mailing_list',
        ),
    ]
